config/routes.rb
Rails.application.routes.draw do
  resources :reviews
  get 'reviews/index'
  get 'user_reviews/:user_id' => 'reviews#user', as: :user_reviews

  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clearCart'
  get '/cart/:id'=> 'cart#add'
  delete '/cart/:id' => 'cart#destroy'

  get 'user/index'

  get 'user/show'



 get 'gender/:gender/shoes' => 'shoes#index'

 resources :shoes do
     resources :reviews
 end

  get 'welcome/index'
  resources :categories do
    resources :shoes  do
      collection do
        get :men
        get :women
        get :kids
      end
    end
     get 'gender/:gender/shoes' => 'shoes#index'
  end


  resources :shoes
    resources :reviews
  # resources :users
  root "welcome#index"
  devise_for :users

end

app/models/categories_shoes.rb
class CategoriesShoes < ActiveRecord::Base
  belongs_to :category
  belongs_to :shoe
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_and_belongs_to_many :shoes

  def image
    shoes.where("image is not null").try!(:first).try!(:image)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :shoe
end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  has_and_belongs_to_many :categories
  has_many :reviews
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :reviews
  # include FriendlyId

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
      devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
      devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
      devise_parameter_sanitizer.for(:sign_out) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }

    end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
    id=params[:id]
    logger.info id

  if session[:cart] then
    cart=session[:cart]
  else
    session[:cart]={}
    cart=session[:cart]
  end

    if cart[id] then
      cart[id]=cart[id] +1
    else cart[id]=1

    end
    logger.info cart
    redirect_to cart_path
  end

  def clearCart
    session[:cart]=nil
    redirect_to cart_path

  end

  def index
    if session[:cart] then
      @cart=session[:cart]
    else @cart={}

  end
end

  def destroy
    session[:cart].delete(params[:id])

    redirect_to cart_path
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.joins(:shoes).all.uniq
  end
end

app/controllers/footer_controller.rb
class FooterController < ApplicationController
  def contact
  end

  def our_story
  end

  def brands
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, only: [:create]
  def create
    review_params = params.require( :review ).permit( :message )

    @review = Review.new( message: review_params[:message], user: current_user )

    if @review.save
       redirect_to reviews_path
    else
       render reviews_path
    end
 end

  def index
    @shoe = Shoe.find(params[:shoe_id])
    @reviews = @shoe.try!(:reviews)
  end

  def user
      @user = User.find( params[:user_id] )
      @reviews = Review.where( user: @user ).order( created_at: :desc )
   end

end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def show
    @shoe = Shoe.find(params[:id])
  end

  def men
    params[:gender] = 'man'
    index
    render :index
  end

  def women
    params[:gender] = 'woman'
    index
    render :index
  end

  def kids
    params[:gender] = 'kids'
    index
    render :index
  end

  def index
    if params[:search]
      shoes = Shoe.where("shoes.name iLIKE ?", "%#{params[:search]}%")
      if shoes.present?
        @shoes = shoes
      else
        redirect_to shoes_path, notice: "Sorry, we have no results for your search!"
      end
    else
      @shoes = Shoe.all
    end
    @shoes = @shoes.joins(:categories).where(categories:{id: params[:category_id]}) if params[:category_id].present?
    @shoes = @shoes.where(gender:[params[:gender],"unisex"]) if params[:gender].present?
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @categories = Category.joins(:shoes).all.uniq
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cart/index.html.erb
<div class="container">
<h1>Your cart have: </h1>

<%@total_price=0%>


<div class="row">
  <%@cart.keys.each do |id|%>
  <ul>
    <%product=Shoe.find_by_id(id)%>
    <li class="cart-list">
      <%= image_tag(product.image, class: "img-cart") %>
    </li>
    <li class="cart-list">
      <label><%=product.name%></label>
      <p>Price per unit: <%=product.price%> euros.</p>
      <%= link_to "Delete product", "/cart/#{product.id}", method: :delete %>
      <%@total_price=@total_price+product.price%>
    </li>
    <br>
    <br>
  </ul>
  <%end%>
</div>

<% if @total_price>0%>
<h3>The total in your shopping cart is: <%=@total_price%> euros</h3>
<br/>
<% else%>
<%end%>


<%=link_to "Buy more products", shoes_path, class: "btn btn-default"%> |
<%=link_to "Empty your cart", cart_clear_path, class: "btn btn-default"%>
</div>

app/views/categories/index.html.erb
<section class="container">
    <div class="row">
    <% @categories.each do |category| %>
    <div class="col-xs-6 col-md-4 col-lg-3">
      <div class="thumbnail">
        <%= link_to image_tag(category.image, class: "img-index"), category_shoes_path(category)  %>
        <div class="background-caption">
          <p><%= category.name %></p>
        </div>
      </div>
    </div>
  <% end %>
 </div>
</section>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="footer">
    <ul class="nav navbar-nav">
        <li><%= link_to "Contact", root_path, class: "btn btn-xs" %> </li>
        <li><%= link_to "Our Story", root_path, class: "btn btn-xs" %></li>
        <li><%= link_to "Terms & Conditions", root_path, class: "btn btn-xs" %></li>
        <li><%= link_to "Brands", root_path, class: "btn btn-xs" %></li>
    </ul>
  </div>
  <div class="footer-row">
    <div class="row">
      <h5>Built with little knowledge, lots of enthusiasm, and gigantic amount of <span class="glyphicon glyphicon-heart-empty"></span><span class="glyphicon glyphicon-heart-empty"></span><span class="glyphicon glyphicon-heart-empty"></span>!</h5>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-togle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Home</a>
    </div>
    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="<%= root_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Men <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @manscategories = Category.joins(:shoes).where(shoes:{gender:["man","unisex"]}).uniq%>
            <% @manscategories.each do |category| %>
              <li><%= link_to category.name, men_category_shoes_path(category) %></li>
            <%end%>
          </ul>
        </li>
        <li class="dropdown">
          <a href="<%= root_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Women <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @womanscategories = Category.joins(:shoes).where(shoes:{gender:["woman","unisex"]}).uniq%>
            <% @womanscategories.each do |category| %>
              <li><%= link_to category.name, women_category_shoes_path(category) %></li>
              <%end%>
          </ul>
        </li>
        <li class="dropdown">
          <a href="<%= root_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Kids <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <% @kidscategories = Category.joins(:shoes).where(shoes:{gender:"kids"}).uniq%>
            <% @kidscategories.each do |category| %>
              <li><%= link_to category.name, kids_category_shoes_path(category) %></li>
            <%end%>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path, class: "btn" %></li>
        <% else %>
          <li><span class="navbar-text"><%= current_user.email %></span></li>
          <li><%= link_to "Log Out", destroy_user_session_path, class: "btn", :method => :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<div class="search-btn">
  <%= form_tag '/shoes', :method => 'get', id: "search-form", class: "navbar-form", role:"search" do %>
    <div class="form-group">
      <p class="search">
        <%= text_field_tag :search, params[:search], placeholder: "Search name", class: "form-control" %>
        <%= submit_tag "Search", :name => nil, class: "btn" %>
      </p>
    </div>
    <div class="cart-trolley">
      <a href="/cart"><span class="glyphicon glyphicon-shopping-cart"></span></a>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Shoestore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Francois+One' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=EB+Garamond' rel='stylesheet' type='text/css'>
</head>
<body>
  <img src="http://www.designbolts.com/wp-content/uploads/2012/12/Classic-45-degree-seamless-pattern-for-website-background.jpg" id="bg">
  <%= render "layouts/header" %><br/>

  <div class="main">
    <p class="notice" >
      <% unless notice.nil? %>
        <div class="notice-msg">
          <%= notice %>
        </div>
      <% end %>
    </p>
    <p class="alert">
      <% unless alert.nil? %>
        <div class="alert-msg">
          <%= alert %>
        </div>
      <% end %>
    </p>

    <%= yield %>


  </div>

  <%= render "layouts/footer" %>
</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for ([@shoe, Review.new]) do |f| %>

    <div class="input-group col-xs-12">
      <div class="col-xs-8"><%= f.text_area :message, class: "form-control", rows:"4", placeholder:"Write your Review here"%></div>
      <div class="col-xs-4"><%= f.submit "Submit", class: "btn" %></div>
    </div>
<% end %>

app/views/reviews/_review.html.erb
<div>
  <blockquote>
    <p>"<%= review.message %>"</p>
    <footer>
        <%= review.user.email %>
        <em><%= link_to "See other reviews by this user", user_reviews_path( review.user ) %>
      </em></footer>
  </blockquote>
</div>

app/views/reviews/index.html.erb
<div class="text-center"><h3>Here is what our Customers say about <strong><%= @shoe.name %></strong> </h3>
<%= image_tag( @shoe.image, width:"100", height:"auto" ) %></div>


<br>

<%= render @reviews %>

<br>
<em>Tried this Product? Tell us about it!</em>
<% if current_user then %>
  <%= render "form" %>
<% else%>
  <br>
    <p class="text-danger"><strong>You must log in before you can write a review</strong></p>
<%end%>
<br>
<p><%= link_to "Back to Show Page", @shoe %></p>

app/views/reviews/user.html.erb
<h1><%= "Reviews by " + @user.email %></h1>

<br>

<% @reviews.each do |review| %>
<div>
  <blockquote>
    <p>"<%= review.message %>"</p>
    <footer><p>Review for
      <%= link_to review.shoe.name, review.shoe %>
    <%= image_tag( review.shoe.image, width:"100", height:"auto" ) %></p>
    </footer>
  </blockquote>
</div>
<% end %>

app/views/shoes/index.html.erb
<div class="container">
  <div class="wrapper">
    <div class="sale-txt">50% SALE</div>
    <div class="sub-sale-txt">*on selected items</div>
  </div>

<br/>

  <div class="row">
    <% @shoes.each do |shoe| %>
        <div class="col-sm-12 col-md-4">
          <div class="thumbnail">
            <div class="shoe-thumb"
              <%= link_to image_tag(shoe.image, class: "img-index"), shoe %>
              <div class="caption">
                <div class="text-title"><%= link_to shoe.name, shoe %></div>
                <p><strong>Price: </strong><span class="glyphicon glyphicon-euro"></span> <%= shoe.price %></p>
                <p><%= shoe.description %></p>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>
</div>

app/views/shoes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-5">
      <div class="template">
        <div class="left-side">
          <%= image_tag( @shoe.image, class: "img-show" ) %>
        </div>
        <div class = "title-background"><h1 class = "big-title"><%= @shoe.name %></h1>
        </div>
      </div>
    </div>

    <div class = "col-sm-12 col-md-7">
      <div class = "text-background">
        <h3 class = "text-title">Brand: <%= @shoe.brand %></h3>
        <div class = "text-block">

              <% if @shoe.color != nil %>
                <h3 class = "text-text">Color: <%= @shoe.color %></h3>
              <%end%>
              <h3 class = "text-text">Price: <%= @shoe.price %>  €</h3>
              <% if @shoe.stock < 15 %>
                <h3 class = "text-text text-danger">Only <%= @shoe.stock %> left in stock!</h3>
              <%end%>

        </div>
        <div>
            <h3><a class = "btn btn-default btn-lg button-card" href="/cart/<%=@shoe.id%>">Add to cart</a></h3>
            <h3><a class = "btn btn-default btn-lg" href="/categories/">Go Back</a></h3>

      </div>
       </div>
    </div>
   </div>
  </div>
<br>
<% if @shoe.reviews.count > 0 %>
  <h4 class="rev-note">
    <%= link_to "Read all " + @shoe.reviews.count.to_s + " reviews", shoe_reviews_path(@shoe.id) %>
  </h4>
<%end%>

app/views/users/index.html.erb
<h1>User#index</h1>
<% @users.each do |user| %>
    <p><%= link_to user.name, user %></p>
<% end %>

app/views/users/show.html.erb
<h1>User#show</h1>
<p>Find me in app/views/user/show.html.erb</p>

app/views/welcome/index.html.erb
<section class="container">
    <div class="row">
    <% @categories.each do |category| %>
       <div class="col-xs-6 col-md-4 col-lg-3">
          <div class="thumbnail">
            <%= link_to image_tag(category.image, class: "img-index"), category_shoes_path(category)  %>
            <div class="background-caption">
              <p><%= category.name %></p>
            </div>
          </div>
       </div>
    <% end %>
   </div>
</section>